### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by yarox24** [att/docker-forensics#1]
https://github.com/att/docker-forensics/blob/379e04e5677e57bce62b5484d386c12e340797d9/mac-robber.py#L133

This fragment should be string not int ?

Tested on: Linux, Python 3.10, pystatx not installed

Traceback:
```
Traceback (most recent call last):
  File "/tmp/mac-robber.py.orig", line 214, in <module>
    outstr = process_item(dirpath, directory)
  File "/tmp/mac-robber.py.orig", line 147, in process_item
    md5str
TypeError: can only concatenate str (not "int") to str
```

**Comment by clausing** [comment]
Sigh... not sure how I missed casting those. It actually worked on the system where I tested it out. It is fixed now.
